# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0003_auto_20171116_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='p_photo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
