# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0004_auto_20171116_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about',
            field=models.CharField(default='I am me', max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='dept',
            field=models.CharField(default='dept', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='designation',
            field=models.CharField(default='Designation', max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(default='eMAIL', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='first_name',
            field=models.CharField(default='FIRST_NAME', max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='institute_name',
            field=models.CharField(default='Institute', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='last_name',
            field=models.CharField(default='LAST_NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(default='999999999', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
