# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0009_auto_20171116_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='p_photo',
            field=models.ImageField(blank=True, default='12.jpg', null=True, upload_to='media'),
        ),
    ]
