# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0010_auto_20171116_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='p_photo',
            field=models.FileField(default='12.jpg', upload_to='media'),
        ),
    ]
