# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0017_auto_20171117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='link',
            field=models.CharField(default='emptylink', max_length=1000),
        ),
    ]
