# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0018_info_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(default='EMAIL', max_length=100),
        ),
    ]
