# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infop', '0019_auto_20171119_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='link',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
