# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(default=1, max_length=100)),
                ('send', models.CharField(default=1, max_length=100)),
                ('sender', models.CharField(default=1, max_length=100)),
                ('inbox', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='teaching',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
