# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mailing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 18, 7, 31, 59, 494607)),
        ),
    ]
