# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171118_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='count2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 19, 6, 2, 1, 171753)),
        ),
    ]
