# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 02:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20171119_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='count1',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='count2',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send',
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 19, 7, 39, 48, 528740)),
        ),
    ]
