# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171119_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='user',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 19, 7, 44, 25, 541524)),
        ),
    ]
