# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171119_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 19, 17, 26, 25, 454928)),
        ),
    ]
