# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171119_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 20, 14, 5, 50, 781823)),
        ),
    ]
