# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20171120_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 21, 3, 34, 18, 447451)),
        ),
    ]
