# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171117_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
