# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171117_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_photo',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
