# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=models.CharField(max_length=5000),
        ),
    ]
